name: BuildNTest

on:
  push:
    branches: [ main, develop, backend ]
  pull_request:
    branches: [ main, develop, backend ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore
      working-directory: backend
    - name: Build
      run: dotnet build --no-restore
      working-directory: backend
    - name: Unit Tests
      run: dotnet test UnitTests --no-build --verbosity normal
      working-directory: backend
    - name: Integration Tests
      run: dotnet test IntegrationTests --no-build --verbosity normal
      working-directory: backend